# Generated by Django 5.1.3 on 2024-12-07 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.IntegerField(default=0, help_text='enter product price here')),
                ('added_in', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=160)),
                ('rcg_tag', models.CharField(choices=[('sd_wht', 'only white piece'), ('sd_col', 'one color piece'), ('mx_col', 'mixed color piece')], default='mx_col', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='product_photos')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ecom.product')),
            ],
        ),
    ]
