# Generated by Django 5.1.3 on 2024-12-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('nk', 'NECKLACE'), ('hd', 'BRACELET'), ('bag', 'MULTI PURPOSE BAG')], default='hd', max_length=15),
        ),
    ]
