# Generated by Django 5.1.3 on 2024-12-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='face_pic',
            field=models.ImageField(default='none', upload_to='face_photos'),
        ),
    ]
